spring:
 datasource:
  driver-class-name: org.sqlite.JDBC
  url: jdbc:sqlite:/Users/kylezeng/develop/workspace/xcep/db/xbcp.db
  username:
  password:
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
pagehelper:
  auto-dialect: true